server:
  port: 8082

dubbo:
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://127.0.0.1:2181
  application:
    name: dubbo-provider-demo1
  scan:
    base-packages: com.example.dubbo.services.impl
